import type { Metadata } from "next";
import { Fira_Code, Inter, Lato, Merriweather } from "next/font/google";

import "./globals.css";
import { ThemeProvider } from "@app/providers/theme-provider";

const interFont = Inter({ subsets: ["latin"], variable: "--font-serif" });
const merriweatherFont = Merriweather({
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"],
  variable: "--font-sans",
});
const firaFont = Fira_Code({
  subsets: ["latin"],
  variable: "--font-mono",
  preload: true,
});
const latoFont = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${interFont.variable || merriweatherFont.variable || firaFont.variable || latoFont.variable}`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
