import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Header from '@app/components/Header.component'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={`${inter.className}`}>
        <Header device='mobile'/>
        {children}
      </body>
    </html>
  )
}
